#ifndef JSON_GEN_H_GUARD
#define JSON_GEN_H_GUARD
#include "globalVariables.h"
#include <time.h>
#include <sys/time.h>

#define JSON_FORMAT_STRING_START "{\"mac:dateTime\":\"%02x:%02x:%02x:%02x:%02x:%02x:%u\""
#define JSON_FORMAT_STRING_FIELD_START ",\"%s\":\""
#define JSON_FORMAT_STRING_FIELD_END "\""
#define JSON_FORMAT_STRING_FIELD( format ) JSON_FORMAT_STRING_FIELD_START format JSON_FORMAT_STRING_FIELD_END
#define JSON_FORMAT_STRING_END "}"

#define _JSON_FORMAT_BUILDER1( nxtSpec ) JSON_FORMAT_STRING_FIELD(nxtSpec)
#define _JSON_FORMAT_BUILDER2( nxtSpec, ... ) JSON_FORMAT_STRING_FIELD(nxtSpec) _JSON_FORMAT_BUILDER1(__VA_ARGS__)
#define _JSON_FORMAT_BUILDER3( nxtSpec, ... ) JSON_FORMAT_STRING_FIELD(nxtSpec) _JSON_FORMAT_BUILDER2(__VA_ARGS__)
#define _JSON_FORMAT_BUILDER4( nxtSpec, ... ) JSON_FORMAT_STRING_FIELD(nxtSpec) _JSON_FORMAT_BUILDER3(__VA_ARGS__)
#define _JSON_FORMAT_BUILDER5( nxtSpec, ... ) JSON_FORMAT_STRING_FIELD(nxtSpec) _JSON_FORMAT_BUILDER4(__VA_ARGS__)
#define _JSON_FORMAT_BUILDER6( nxtSpec, ... ) JSON_FORMAT_STRING_FIELD(nxtSpec) _JSON_FORMAT_BUILDER5(__VA_ARGS__)
#define _JSON_FORMAT_BUILDER7( nxtSpec, ... ) JSON_FORMAT_STRING_FIELD(nxtSpec) _JSON_FORMAT_BUILDER6(__VA_ARGS__)
#define _JSON_FORMAT_BUILDER8( nxtSpec, ... ) JSON_FORMAT_STRING_FIELD(nxtSpec) _JSON_FORMAT_BUILDER7(__VA_ARGS__)
#define _JSON_FORMAT_BUILDER9( nxtSpec, ... ) JSON_FORMAT_STRING_FIELD(nxtSpec) _JSON_FORMAT_BUILDER8(__VA_ARGS__)
#define JSON_FORMAT_BUILDER(num, ...) JSON_FORMAT_STRING_START _JSON_FORMAT_BUILDER##num(__VA_ARGS__) JSON_FORMAT_STRING_END
#define JSON_NUM "%d"
#define JSON_FLOAT "%f"
#define JSON_STRING "%s"

#define JSON_TO_BUF( JSON_SPEC, BUF_LEN, BUF, ... ) snprintf( BUF, BUF_LEN, JSON_SPEC, MAC_ADDRESS[ 0 ], MAC_ADDRESS[ 1 ], MAC_ADDRESS[ 2 ], \
MAC_ADDRESS[ 3 ], MAC_ADDRESS[ 4 ], MAC_ADDRESS[ 5 ], (unsigned)time(NULL), __VA_ARGS__ )

#endif
